using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GZFuel.Model.Entities
{
    public  class TransactionLine : BaseEntity
    {
        //properties 
        public int ID { get; set; }
        public int Quantity { get; set; }
        public decimal ItemPrice { get; set; }
        public decimal TotalValue { get; set; }
        public decimal DiscountPercent { get; set; }

        public decimal NetValue { get; set; }
        public decimal DiscountValue { get; set; }


        // constructor
        public TransactionLine(int quantity, decimal itemPrice, decimal totalValue, decimal discountPercent, decimal discountValue)
        {
            // ID = id; not here , the ID is auto generated by the database



            //-- calculations 
            NetValue = quantity * itemPrice;
            DiscountValue = (NetValue * discountPercent);
            TotalValue = NetValue - DiscountValue;

            TotalValue = TotalValue - (TotalValue * FuelDiscount()); // PX 100 - (100 * 0.1) = 90


            DiscountPercent = discountPercent;
            DiscountValue = discountValue;
        }


        // relationships
        public int TransactionID { get; set; }
        public Transaction Transaction { get; set; }
        public int ItemID { get; set; }
        public Item Item { get; set; }





        // methods

        // Discount for fuel will be moved to the controllers of Web Api project

        public decimal FuelDiscount()
        {
            // i dont know if it will work :/ 
            decimal discount = 0;
            if (Enum.GetName(Item.ItemType) == "fuel" && NetValue > 20)
            {
                discount = 0.1m;
            }
            return discount;
        }




    }






}
