using GZFuel.Model.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GZFuel.Model.Entities
{
    public class Transaction
    {
        /**
         *  Transaction: ID, Date, EmployeeID, CustomerID, 
         *  PaymentMethod (enum), TotalValue
         * 
         */

          public int ID { get; set; }
          public DateTime Date { get; set; }
          public int EmployeeID { get; set; }
         public int CustomerID { get; set; }
         public PaymentMethod PaymentMethod { get; set; }
          public decimal TotalValue { get; set; }


         public Transaction(int id,  int employeeID, int customerID, PaymentMethod paymentMethod, decimal totalValue)
        {
            // ID = id; not here , the ID is auto generated by the database
            Date = DateTime.Now;

            EmployeeID = employeeID;
            
            CustomerID = customerID;

            PaymentMethod = paymentMethod;

            TotalValue = totalValue; // will have to calculate that but calculating all the transactionlines in it 
            
        }



    }
}
